---
- hosts: all
  remote_user: root
  tasks:
    - name: Create a password for the 'ansible' user.
      set_fact:
        ansible_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
    - name: Create the 'ansible' user.
      user:
        name: ansible
        password: "{{ ansible_password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        update_password: on_create
    - name: Set authorized key for the 'ansible' user.
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', authorized_key) }}"
    - name: Print the password for the user 'ansible'.
      debug:
        msg: "The password for 'ansible' is {{ ansible_password }}"