---
- hosts: all
  vars_prompt:
    - name: ansible_password
      prompt: "What is the password for the 'ansible' user?"
  remote_user: ansible
  become: yes
  vars:
    ansible_become_pass: "{{ ansible_password }}"
  tasks:
  - name: Reboot the machine
    reboot:
      msg: Ansible will now reboot the machine!